### ISSUE TITLE
Not working distress signal

### ISSUE THREAD

**Issue by Jackpoter135** [esx-framework/esx_ambulancejob#11]
I try to fix the distress signals but when i try to send signal with the default phone that was used for the resource still the distress signals not working no errors just it didn't work

**Comment by Gellipapa** [comment]
@Jackpoter135 Hi! Which phone resource use?

**Comment by Gellipapa** [comment]
@Jackpoter135 Hi! Yes default phone not support distress signal, and NPWD not support job chat but you can see player blip in map when someone call help.
