### ISSUE TITLE
Can´t open any menu

### ISSUE THREAD

**Issue by Silverquest91** [esx-framework/esx_ambulancejob#31]
I cant open any menu vehicleshop warderobe whatelse

**Comment by Gellipapa** [comment]
What? You need download latest esx_core it's includes esx_contextmenu and this is use ambulancejob.

**Comment by Silverquest91** [comment]
no i have the latest esx_core

**Comment by Silverquest91** [comment]
okay it works .. i load contextmenu .. but i use native oder esx_menu with nativ rework ..

**Comment by Gellipapa** [comment]
No esx issue, i closed.
