### ISSUE TITLE
if you buy a car in the shop, you have that in your garage

### ISSUE THREAD

**Issue by JeremySmitss** [esx-framework/esx_ambulancejob#38]
If you buy a ambulance in the ambulanceshop, the car will be returned in your own garage. I use esx_jb_eden_garage for my own cars buyed in the cardealer. But the ambulance are in my private garage

**Comment by Gellipapa** [comment]
Hi! @JeremySmitss  Probably the problem is not in esx_ambulancejob, the script registers the car in the owned_vehicles table under a certain type. If this is not handled by esx_jb_eden_garage it will show up in your garage.

**Comment by Gellipapa** [comment]
![image](https://github.com/esx-framework/esx_ambulancejob/assets/22717950/35583189-6f1d-4cfe-8102-fbecd989705f)
Hi! I retest your reported issue, and it's works perfectly. You should update latest esx_core and esx_ambulance or fix issue in esx_jb_eden_garage. This is not offical ESX resource.
