### ISSUE TITLE
"Your vehicle is not stored in the garage"

### ISSUE THREAD

**Issue by blackSheep66YT** [esx-framework/esx_ambulancejob#39]
Hey, as soon as I buy an ambulance I cant spawn it because its supposedly not in the garage. In owned_vehicles (in the database) its registered that I bought an ambulance as an medic. 
Could you please help me?

**Comment by Gellipapa** [comment]
@blackSheep66YT Hi! Can you take any video? I can't reproduce latest version this problem. I can buy ambulance vehicle and can spawn/store.
