### ISSUE TITLE
Death timer not showing

### ISSUE THREAD

**Issue by Warmarcus** [esx-framework/esx_ambulancejob#41]
As sayed in the title i have a problem with my death timer.
my version: 1.2.0
i was wondering if you could help me

**Comment by Gellipapa** [comment]
@Warmarcus Hi! What do you mean? Please take a photo and send me. You should download latest esx_ambulancejob.

**Comment by Warmarcus** [comment]
Hey The latest version dosent support our needs, it has worked before but now it dosent i dont know why
but here is the picture.
As you can see he is dead but no timer at the buttom of his death
https://cdn.discordapp.com/attachments/937037270391857245/1146803471232794757/Skrmbillede_2023-08-31_154720.png

**Comment by Gellipapa** [comment]
> Hey The latest version dosent support our needs, it has worked before but now it dosent i dont know why but here is the picture. As you can see he is dead but no timer at the buttom of his death https://cdn.discordapp.com/attachments/937037270391857245/1146803471232794757/Skrmbillede_2023-08-31_154720.png
> 
> Also admin revive (/revive ID) dosent revive us

Hi! Thank you for reply. Can you send me any error message when you die?  F8 in console, or server console?

**Comment by Warmarcus** [comment]
Hi,
No errors just dosen't appear. i have also fixed one thing in the script that made the dead person crash i can't remember the error anymore. i you want you can add me and i can screenshare.

Discord: Warmarcus / Marcus H#6035

**Comment by Gellipapa** [comment]
Hi! Sorry, but you need to use the latest version of es_extended and esx_ambulancejob, the old version is no longer supported.
