### ISSUE TITLE
Your vehicle is not stored in the garage.

### ISSUE THREAD

**Issue by BaifernOEI** [esx-framework/esx_ambulancejob#57]
vehicle.lua

I've edited lines 61-65 I tried printing it and it seems to use boolean, not number
So I added v.stored == true/false  to it and it worked fine. :

```
if v.stored == 1 or v.stored == true then
								label = label .. ('<span style="color:green;">%s</span>'):format(TranslateCap('garage_stored'))
							elseif v.stored == 0 or v.stored == false then
								label = label .. ('<span style="color:darkred;">%s</span>'):format(TranslateCap('garage_notstored'))
							end
```
[client.zip](https://github.com/user-attachments/files/16321641/client.zip)

**Comment by Gellipapa** [comment]
@BaifernOEI Hi! Fixed. Thanks for report problem.
