### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by Kiminaze** [esx-framework/esx_ambulancejob#58]
Hey :)

This code here looks awfully familiar:
https://github.com/esx-framework/esx_ambulancejob/blob/main/client/main.lua#L387-L481

I did not remember giving anyone permission to use this anywhere. The original code can be found here: https://github.com/Kiminaze/DeathCam

I have no clue how long this has been in this resource but according to the commit history at least since January of 2023. At that point, my Deathcam did not even include a License. And a few months after that I added one that does still not permit anyone from distributing it in other releases. No license = you can fork it and look at it, nothing else.

I am willing to talk about it before I take any other action since this is a major release in the community.

Kind regards, Kiminaze

**Comment by Gellipapa** [comment]
@Kiminaze Hi!

Thank you for raising your concern. This code was approved by the previous management and I apologise on their behalf. 

I am currently leading the ESX development so I would ask how we can continue to use your code or if that is not possible or you do not authorize the use of the code then let us know and we will write it ourselves. 

Unfortunately I didn't know this when I came to the project that copyrighted code was used, so again I apologize and look forward to your reply in advance thank you.

**Comment by Kiminaze** [comment]
Hey @Gellipapa ,

Thank you for the fast reply and I accept the apology.

I am currently in the process of updating many of my old resources to be a little more up-to-date. My `DeathCam` was not one of those since I've made the `OrbitCam` which completely replaces the `DeathCam` anyways while also allowing for much more customizability.

I will add a new license to the `DeathCam` repository (the old one has run out anyways) and add an "exception" clause to it that will allow using it if permission has been granted. The only thing I will ask you to include is a notice above the code once I've done that.
I will update this issue once the license has been udpated.

**Comment by Kiminaze** [comment]
To @Gellipapa,

I am hereby granting you and the "esx-framework" GitHub organization explicit written permission to publish and/or distribute parts of the software known as "DeathCam" published by me. This permission is granted under the following conditions:

1. You are permitted to publish and/or distribute the contents of the file "client.lua" of the software.
2. This permission is granted solely for the purpose of adding to the GitHub repository "esx_ambulancejob" from the "esx-framework" organization for non-commercial use only.
3. Appropriate credit must be given to the original author and copyright holder of the software. It should contain my name, developer alias and a link to the original repository. (a valid example can be seen below)

I reserve the right to withdraw this permission at any time.

This permission is effective as of 25 July 2024.

If you have any questions or require further clarification, please do not hesitate to contact me or update this issue.

Thank you for your cooperation.

Sincerely,

Kiminaze / Philipp Decker


Example for the copyright notice:
```
Copyright for the camera controls:
Philipp Decker (alias Kiminaze)
Original source: https://github.com/Kiminaze/DeathCam
```

**Comment by Gellipapa** [comment]
@Kiminaze Hi! Thanks for the opportunity on behalf of ESX, but this breaks our license at a few points.

Under their license, redistribution is not allowed, while under our license, redistribution is allowed.

While your license says non-commercial, our license says commercial.

This will result in a license violation, which we will not do, so presumably if you don't release this older version (with some more open license) with only the current license, we will have to write our own camera logic for it.

I hope you understand what our problem is, we are not going to break the current license for this one script, and unfortunately I can't comment on the past, for which I still apologize, but I didn't have it this time.

**Comment by Arctos2win** [comment]
> To @Gellipapa,
> 
> I am hereby granting you and the "esx-framework" GitHub organization explicit written permission to publish and/or distribute parts of the software known as "DeathCam" published by me. This permission is granted under the following conditions:
> 
> 1. You are permitted to publish and/or distribute the contents of the file "client.lua" of the software.
> 2. This permission is granted solely for the purpose of adding to the GitHub repository "esx_ambulancejob" from the "esx-framework" organization for non-commercial use only.
> 3. Appropriate credit must be given to the original author and copyright holder of the software. It should contain my name, developer alias and a link to the original repository. (a valid example can be seen below)
> 
> I reserve the right to withdraw this permission at any time.
> 
> This permission is effective as of 25 July 2024.
> 
> If you have any questions or require further clarification, please do not hesitate to contact me or update this issue.
> 
> Thank you for your cooperation.
> 
> Sincerely,
> 
> Kiminaze / Philipp Decker
> 
> Example for the copyright notice:
> 
> ```
> Copyright for the camera controls:
> Philipp Decker (alias Kiminaze)
> Original source: https://github.com/Kiminaze/DeathCam
> ```

Dear @Kiminaze,

Thank you for your prompt response and for offering the "DeathCam" script for our use. We understand and respect the licensing constraints you have highlighted.

Given the incompatibility of our licenses, we have already rewritten the necessary camera logic for the "esx_ambulancejob" repository. Therefore, we will not be utilizing the original "DeathCam" code.

We consider this issue now as resolved and appreciate your understanding and cooperation.

Thank you.

Sincerely,

@Arctos2win 
Management, ESX

**Comment by Kiminaze** [comment]
I'm sorry we couldn't make this work. But this might just be for the better for both of us!

I keep my things and you now actually have up-to-date and more performant code.

Thank you for understanding as well.

Sincerely,
Kiminaze
