### ISSUE TITLE
if a player die and quit game , when he join game he is alive

### ISSUE THREAD

**Issue by RoccoRP** [esx-framework/esx_ambulancejob#61]
if a player die and quit game , when he join game he is alive

**Comment by Gellipapa** [comment]
@RoccoRP Hi! Do you use esx_multicharacter?

**Comment by Gellipapa** [comment]
![Image](https://github.com/user-attachments/assets/8b79743a-67c1-424b-96f9-a2c592a5daaf)
Latest version, i tested works perfectly.

**Comment by Gellipapa** [comment]
I tested, multicharacter and works perfectly. ![Image](https://github.com/user-attachments/assets/e69547ff-d882-4d43-aabf-d9eb90a0045e)
Look at the esx_ambulancejob in the config and Config.SaveDeathStatus is set to true.

**Comment by RoccoRP** [comment]
ok thank you so much !
