### ISSUE TITLE
Players can speak on death

### ISSUE THREAD

**Issue by Zzeyy** [esx-framework/esx_ambulancejob#8]
Players can speak after they die.
I've made no edits to the script.

**Comment by ProxyPing** [comment]
> Players can speak after they die. I've made no edits to the script.

You need to edit the script, u use saltychat?

**Comment by Gellipapa** [comment]
@Zzeyy Hi! Which voice system use?

**Comment by Gellipapa** [comment]
We tested and player can't speak if dead, close issue.
